
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000

  # used by export-to-pg example
  postgres:
    image: postgres:latest
    environment:
      PGPORT: 5432
      POSTGRES_DB: "cipherstash"
      POSTGRES_USER: "cipherstash"
      PGUSER: "cipherstash"
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    deploy:
      resources:
        limits:
          cpus: "${CPU_LIMIT:-2}"
          memory: 2048mb
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
