/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = number
export type Kind = 'pt'
export type Table = string
export type Column = string
export type Plaintext = string
/**
 * Specifies that the plaintext should be encrypted for a specific query operation. If null, source encryption and encryption for all indexes will be performed.
 */
export type ForQuery = 'match' | 'ore' | 'unique' | 'ste_vec' | 'ejson_path'

/**
 * The EQL plaintext JSON payload sent by a client (such as an application) to CipherStash Proxy.
 */
export interface CsPlaintextV1Schema {
  v: SchemaVersion
  k: Kind
  i: Ident
  p: Plaintext
  q?: ForQuery
  [k: string]: unknown
}
export interface Ident {
  t: Table
  c: Column
  [k: string]: unknown
}
