import { existsSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import * as p from '@clack/prompts'
import { detectPackageManager, runnerCommand } from '../init/utils.js'

export interface EnvOptions {
  /** Write the emitted block to `.env.production.local` instead of stdout. */
  write?: boolean
}

/**
 * Generate production env vars for CipherStash using the local device-code
 * auth. Today this is a scaffold (CIP-2997): the CTS endpoint that mints a
 * production access key isn't wired up yet, so the command is gated behind
 * the `STASH_EXPERIMENTAL_ENV_CMD` env flag to keep it out of the way until
 * the backend piece lands.
 *
 * Once CTS exposes the mint endpoint, fill in `fetchProdCredentials` below.
 * The emitted format matches what apps in the onboarding flow consume via
 * `process.env.*`, so `--write` produces a file the user can commit into a
 * deployment secrets store.
 */
export async function envCommand(options: EnvOptions = {}): Promise<void> {
  if (!process.env.STASH_EXPERIMENTAL_ENV_CMD) {
    p.log.warn('`env` is experimental and not ready for production use yet.')
    p.log.info(
      'Set STASH_EXPERIMENTAL_ENV_CMD=1 in your environment to try it.',
    )
    return
  }

  const runner = runnerCommand(detectPackageManager(), '').trim()
  const cliRef = `${runner} stash`

  p.intro(`${cliRef} env`)

  const creds = await fetchProdCredentials()
  if (!creds) {
    p.log.error(
      `Could not mint production credentials. Make sure you are logged in: ${cliRef} auth login`,
    )
    process.exit(1)
  }

  const block = formatEnvBlock(creds, cliRef)

  if (options.write) {
    const target = resolve(process.cwd(), '.env.production.local')
    if (existsSync(target)) {
      const overwrite = await p.confirm({
        message: `${target} already exists. Overwrite?`,
        initialValue: false,
      })
      if (p.isCancel(overwrite) || !overwrite) {
        p.cancel('Aborted.')
        return
      }
    }

    writeFileSync(target, block, 'utf-8')
    p.log.success(`Wrote ${target}`)
    p.outro('Done!')
    return
  }

  // Default: print to stdout so users can pipe into secret stores / CI env.
  // Use `console.log` (not `p.*`) so the output is clean for redirection.
  console.log(block)
  p.outro('Done!')
}

interface ProdCredentials {
  clientId: string
  clientKey: string
  workspaceId: string
}

async function fetchProdCredentials(): Promise<ProdCredentials | undefined> {
  // TODO(CIP-2997): call the CTS mint endpoint once it's available. The
  // endpoint shape, auth header, and error codes are TBD — coordinate with
  // the platform team before wiring this up. Until then, return undefined
  // so the experimental command fails loudly rather than silently emitting
  // placeholder credentials.
  return undefined
}

function formatEnvBlock(creds: ProdCredentials, cliRef: string): string {
  return [
    `# Generated by \`${cliRef} env\` — production credentials`,
    `CS_CLIENT_ID=${creds.clientId}`,
    `CS_CLIENT_KEY=${creds.clientKey}`,
    `CS_WORKSPACE_ID=${creds.workspaceId}`,
    '',
  ].join('\n')
}
