packages:
  - "packages/*"
  - "examples/*"

catalogs:
  # Can be referened as catalog:repo
  repo:
    tsup: 8.4.0
    typescript: 5.6.3
    tsx: 4.19.3
    vitest: 3.1.3

  security:
    '@clerk/nextjs': 6.31.2
    next: 15.5.7
    vite: 6.4.1
