/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CsEncryptedV1Schema = (
  | {
      k?: 'pt'
      [k: string]: unknown
    }
  | {
      k?: 'ct'
      [k: string]: unknown
    }
  | {
      k?: 'en'
      [k: string]: unknown
    }
) & {
  s?: SchemaVersion
  v: ConfigurationVersion
  k: Kind
  i?: Ident
  p?: Plaintext
  c?: Ciphertext
  'u.1'?: UniqueIndex
  'o.1'?: OreIndex
  'm.1'?: MatchIndex
  [k: string]: unknown
}
/**
 * The schema version of this json document
 */
export type SchemaVersion = 1
export type ConfigurationVersion = number
export type Kind = 'pt' | 'ct' | 'en'
export type Table = string
export type Column = string
export type Plaintext = string
export type Ciphertext = string
export type UniqueIndex = string
/**
 * @minItems 1
 */
export type OreIndex = [string, ...string[]]
/**
 * @minItems 1
 */
export type MatchIndex = [number, ...number[]]

export interface Ident {
  t: Table
  c: Column
  [k: string]: unknown
}
